name: reviewdog
on: [pull_request]
jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Debug Go
        run: |
          go version
          go env

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.3"

      - name: Debug Go
        run: |
          which go
          go version
          go env

      - name: Download Go modules
        run: go mod vendor

      # - name: Run GolangCI-Lint Action by building from repository
      #   uses: matoous/golangci-lint-action@v1.0.0
      #   with:
      #     config: .github/.golangci.yaml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run golangci-lint with reviewdog
      #   uses: docker://reviewdog/action-golangci-lint:v1.0.4
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     golangci_lint_flags: "-v --config=.github/.golangci.yaml"
      #     tool_name: reporter / lint
      #     level: error

      - name: Debug action
        uses: ./.github/workflows/debug-action
        env:
          GOROOT: /usr/local/go
